[package]
name = "gptman"
version = "0.6.3"
authors = ["Cecile Tonglet <cecile.tonglet@cecton.com>"]
license = "MIT"
edition = "2018"
description = "A GPT manager that allows you to copy partitions from one disk to another"
repository = "https://github.com/cecton/gptman"
homepage = "https://github.com/cecton/gptman"
documentation = "https://docs.rs/gptman"
readme = "README.md"
keywords = ["gpt", "partition", "table", "filesystem", "disk"]
categories = ["command-line-utilities"]

[[bin]]
name = "gptman"
path = "src/cli/main.rs"
doc = false
required-features = ["cli"]

[lib]
name = "gptman"

[badges]
travis-ci = { repository = "cecton/gptman" }
is-it-maintained-issue-resolution = { repository = "cecton/gptman" }
is-it-maintained-open-issues = { repository = "cecton/gptman" }
maintenance = { status = "actively-developed" }

[dependencies]
bincode = "1.0.1"
serde_derive = "1.0.114"
serde = "1.0.112"
crc = "1.0.0"
err-derive = "0.2.4"

[dependencies.lazy_static]
version = "1.2.0"
optional = true

[dependencies.ansi_term]
version = "0.12"
optional = true

[dependencies.pad]
version = "0.1"
optional = true

[dependencies.unicode-width]
version = "0.1.5"
optional = true

[dependencies.clap]
version = "2.33"
optional = true

[dependencies.linefeed]
version = "0.6.0"
optional = true

[dependencies.nix]
version = "0.17"
optional = true

[dependencies.rand]
version = "0.7"
optional = true

[dependencies.structopt]
version = "0.3"
optional = true

[features]
default = [ "cli" ]
cli = [ "lazy_static", "ansi_term", "pad", "unicode-width", "clap", "linefeed", "rand", "structopt" ]

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.17"
